# Generated by Django 3.0.8 on 2020-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
